
package GUI;

import LOGIC.Mascota;
import LOGIC.Validacion;
import LOGIC.Veterinario;
import SQL.Conexion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import LOGIC.HistorialMedicos;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author dylan
 */
public class HistorialMedico extends javax.swing.JInternalFrame 
{

    Validacion val = null;
    Conexion conect = null;
    public HistorialMedico() 
    {
        initComponents();
        val = new Validacion();
        val.centrarInternalFrame(this, Principal.desktop_menu);
        cargarComboMasco(cmbIDmascota);
        cargarComboVet(cmbIDVets);
        cmbIDmascota.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        cargarUlltimasVacuDespa();
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombreVet = new javax.swing.JTextField();
        cmbIDmascota = new javax.swing.JComboBox<>();
        FechaVisita = new com.toedter.calendar.JDateChooser();
        txtNombreMasco = new javax.swing.JTextField();
        cmbIDVets = new javax.swing.JComboBox<>();
        cmbMotivoVisita = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMedicamentos = new javax.swing.JTextArea();
        FechaVacuna = new com.toedter.calendar.JDateChooser();
        nombreVacuna = new javax.swing.JTextField();
        fechaDesparasitacion = new com.toedter.calendar.JDateChooser();
        fechaUltimaDespa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaUltimaVacunacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombreVacunaUltima = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(1094, 579));
        setMinimumSize(new java.awt.Dimension(1094, 579));
        setPreferredSize(new java.awt.Dimension(1069, 579));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreVet.setEditable(false);
        txtNombreVet.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreVet.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtNombreVet.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreVet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtNombreVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 150, -1));

        cmbIDmascota.setBackground(new java.awt.Color(255, 255, 255));
        cmbIDmascota.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        cmbIDmascota.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cmbIDmascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        FechaVisita.setBackground(new java.awt.Color(255, 255, 255));
        FechaVisita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FechaVisita.setForeground(new java.awt.Color(0, 0, 0));
        FechaVisita.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(FechaVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 129, -1));

        txtNombreMasco.setEditable(false);
        txtNombreMasco.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreMasco.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtNombreMasco.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreMasco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtNombreMasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, -1));

        cmbIDVets.setBackground(new java.awt.Color(255, 255, 255));
        cmbIDVets.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        cmbIDVets.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cmbIDVets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        cmbMotivoVisita.setBackground(new java.awt.Color(255, 255, 255));
        cmbMotivoVisita.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        cmbMotivoVisita.setForeground(new java.awt.Color(0, 0, 0));
        cmbMotivoVisita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Consulta", "Vacunacion", "Desparasitacion", "Cirugía", "Estetica" }));
        cmbMotivoVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMotivoVisitaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMotivoVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 160, -1));

        txtMedicamentos.setBackground(new java.awt.Color(255, 255, 255));
        txtMedicamentos.setColumns(20);
        txtMedicamentos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtMedicamentos.setForeground(new java.awt.Color(0, 0, 0));
        txtMedicamentos.setRows(5);
        txtMedicamentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtMedicamentos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 434, -1, 100));

        FechaVacuna.setBackground(new java.awt.Color(255, 255, 255));
        FechaVacuna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FechaVacuna.setForeground(new java.awt.Color(0, 0, 0));
        FechaVacuna.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(FechaVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 170, -1));

        nombreVacuna.setBackground(new java.awt.Color(255, 255, 255));
        nombreVacuna.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        nombreVacuna.setForeground(new java.awt.Color(0, 0, 0));
        nombreVacuna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombreVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreVacunaActionPerformed(evt);
            }
        });
        jPanel1.add(nombreVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 191, -1));

        fechaDesparasitacion.setBackground(new java.awt.Color(255, 255, 255));
        fechaDesparasitacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fechaDesparasitacion.setForeground(new java.awt.Color(0, 0, 0));
        fechaDesparasitacion.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(fechaDesparasitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 176, -1));

        fechaUltimaDespa.setEditable(false);
        fechaUltimaDespa.setBackground(new java.awt.Color(255, 255, 255));
        fechaUltimaDespa.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        fechaUltimaDespa.setForeground(new java.awt.Color(0, 0, 0));
        fechaUltimaDespa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fechaUltimaDespa, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 180, -1));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 434, -1, 100));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 184, 252));
        jLabel1.setText("Historial Medico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de visita:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Veterinario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Motivo de visita:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descripcion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        fechaUltimaVacunacion.setEditable(false);
        fechaUltimaVacunacion.setBackground(new java.awt.Color(255, 255, 255));
        fechaUltimaVacunacion.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        fechaUltimaVacunacion.setForeground(new java.awt.Color(0, 0, 0));
        fechaUltimaVacunacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fechaUltimaVacunacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 160, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 112, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Última desparasitación:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Proxima desparasitación:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        nombreVacunaUltima.setEditable(false);
        nombreVacunaUltima.setBackground(new java.awt.Color(255, 255, 255));
        nombreVacunaUltima.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        nombreVacunaUltima.setForeground(new java.awt.Color(0, 0, 0));
        nombreVacunaUltima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(nombreVacunaUltima, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 180, -1));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Medicamentos recetados:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Última vacuna administrada:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Fecha:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre de próxima vacuna:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas_1.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 110, 70));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nombre de Mascota:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("ID:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial-medico.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreVacunaActionPerformed
       
    }//GEN-LAST:event_nombreVacunaActionPerformed

    private void limpiar()
    {
        txtNombreMasco.setText("");
        FechaVisita.setDate(null);
        cmbMotivoVisita.setSelectedItem("-");
        FechaVacuna.setDate(null);
        fechaDesparasitacion.setDate(null);
        txtDescripcion.setText("");
        txtMedicamentos.setText("");
        nombreVacuna.setText("");
        txtNombreVet.setText("");
        fechaUltimaDespa.setText("");
        nombreVacunaUltima.setText("");
        fechaUltimaVacunacion.setText("");  
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
                            conect = new Conexion();
               val = new Validacion();

            if (FechaVisita.getDate() == null || cmbMotivoVisita.getSelectedItem().equals("-") || txtDescripcion.getText().isEmpty()) 
            {
                val.mostrarMensaje("Hay campos que hay que llenar", "Error", "Campos vacios");
                return;
            }

            String motivoVisita = (String) cmbMotivoVisita.getSelectedItem();
            String nombreeVacuna = nombreVacuna.getText();

            if (motivoVisita.equals("Vacunacion") && (nombreeVacuna.isEmpty() || FechaVacuna.getDate() == null)) 
            {
                val.mostrarMensaje("Debe proporcionar el nombre de la vacuna y seleccionar la fecha de vacunación", "Error", "Campos vacíos");
                return;
            }

            if (motivoVisita.equals("Desparasitacion") && fechaDesparasitacion.getDate() == null) 
            {
                val.mostrarMensaje("Debe seleccionar la fecha de Desparasitación", "Error", "Error");
                return;
            }

            if (motivoVisita.equals("Consulta") && txtMedicamentos.getText().isEmpty()) 
            {
                val.mostrarMensaje("Debe proporcionar los medicamentos", "Error", "Error");
                return;
            }


            Date dateVisita = FechaVisita.getDate();
            java.sql.Date fechaVisita = new java.sql.Date(dateVisita.getTime());

            Date dateVacu = FechaVacuna.getDate();
            java.sql.Date fechaVacuna = null;
            if (dateVacu != null) {
                fechaVacuna = new java.sql.Date(dateVacu.getTime());
            }

            Date dateDespa = fechaDesparasitacion.getDate();
            java.sql.Date fechaDespa = null;
            if (dateDespa != null) {
                fechaDespa = new java.sql.Date(dateDespa.getTime());
            }

            int mascoId = (int) cmbIDmascota.getSelectedItem();
            int vetId = (int) cmbIDVets.getSelectedItem();
            String descripcion = txtDescripcion.getText();
            String medicamentos = txtMedicamentos.getText();

            HistorialMedicos HM = new HistorialMedicos();
            HM.setMascotaID(mascoId);
            HM.setVeterinarioID(vetId);
            HM.setFechaVisita(fechaVisita);
            HM.setFechaVacuna(fechaVacuna);
            HM.setDesparasitacion(fechaDespa);
            HM.setMotivoVisita(motivoVisita);
            HM.setNombreVacuna(nombreeVacuna);
            HM.setDescripcion(descripcion);
            HM.setMedicamentos(medicamentos);

            conect.insertHistorialMedico(HM);
            val.mostrarMensaje("Se ha agregado un nuevo registro!", "Info", "Nuevo Historial Medico");
            limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cargarUlltimasVacuDespa()
    {
        DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        conect = new Conexion();
        int idMasco = Integer.parseInt(cmbIDmascota.getSelectedItem().toString());
        HistorialMedicos HM = conect.ultimasVacunasDespa(idMasco);
        if(HM == null)
        {
            fechaUltimaDespa.setText("No hay registros");
            fechaUltimaVacunacion.setText("No hay registros");
            nombreVacunaUltima.setText("No hay registros"); 
        }
        else
        {
            Date fechaDespa = HM.getDesparasitacion();
            String nombreVacu = HM.getNombreVacuna();
            Date fechaVacu = HM.getFechaVacuna();
            if (fechaDespa == null) 
            {
                fechaUltimaDespa.setText("No hay registros");
            } else 
            {
                fechaUltimaDespa.setText(formatoFecha.format(fechaDespa));
            }
            if (fechaVacu == null) 
            {
                fechaUltimaVacunacion.setText("No hay registros");
            } else 
            {
                fechaUltimaVacunacion.setText(formatoFecha.format(fechaVacu));
            }
                 nombreVacunaUltima.setText(nombreVacu);
            
        } 
        
    }
    private void cmbMotivoVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMotivoVisitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMotivoVisitaActionPerformed
    
    public void cargarComboMasco(JComboBox c)
    {
         conect = new Conexion();
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        List<Mascota> listMascoID = conect.obtenerListaIDMascotas();
        
        for(Mascota masco : listMascoID)
        {
            combo.addElement(masco.getId_mascota());
        }
        c.setModel(combo);
        c.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e) 
            {
                int idSeleccionado = (int)c.getSelectedItem();
                String nombreMasco = conect.obtenerNombreMascoPorID(idSeleccionado);
                txtNombreMasco.setText(nombreMasco);
            }
       });
    }
    
    public void cargarComboVet(JComboBox c)
    {
        Conexion conect = new Conexion();
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        List<Veterinario> listVetID = conect.obtenerListaIDMVeterinarios();
        
        for(Veterinario vet : listVetID)
        {
            combo.addElement(vet.getId());
        }
        c.setModel(combo);
        
        c.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                int idSeleccionado = (int)c.getSelectedItem();
                String nombreVet = conect.obtenerNombreVetPorID(idSeleccionado);
                txtNombreVet.setText(nombreVet);
            }
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaVacuna;
    private com.toedter.calendar.JDateChooser FechaVisita;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbIDVets;
    private javax.swing.JComboBox<String> cmbIDmascota;
    private javax.swing.JComboBox<String> cmbMotivoVisita;
    private com.toedter.calendar.JDateChooser fechaDesparasitacion;
    private javax.swing.JTextField fechaUltimaDespa;
    private javax.swing.JTextField fechaUltimaVacunacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreVacuna;
    private javax.swing.JTextField nombreVacunaUltima;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtMedicamentos;
    private javax.swing.JTextField txtNombreMasco;
    private javax.swing.JTextField txtNombreVet;
    // End of variables declaration//GEN-END:variables
}
