
package GUI;


import javax.swing.*;
import java.awt.*;

public class Principal extends javax.swing.JFrame 
{

    public static JDesktopPane desktop_menu;
    
    public Principal() {
        initComponents();
        this.setSize(new Dimension(1370, 661)); // Cambio el tamaño a 1370 x 661
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Veterinaria");
        this.setLayout(null);
        Color customColor = new Color(121, 135, 238);
        jMenu1.setOpaque(true);
        jMenu1.setBackground(customColor);
        jMenu2.setOpaque(true);
        jMenu2.setBackground(customColor);
        jMenu3.setOpaque(true);
        jMenu3.setBackground(customColor);
        jMenu4.setOpaque(true);
        jMenu4.setBackground(customColor);
        jMenu7.setOpaque(true);       
        jMenu7.setBackground(customColor);
        ImageIcon backgroundImage = new ImageIcon(getClass().getResource("/Imagenes/Principal.png"));
        Image image = backgroundImage.getImage();
        Image scaledImage = image.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledBackgroundImage = new ImageIcon(scaledImage);

        JLabel backgroundLabel = new JLabel(scaledBackgroundImage);
        backgroundLabel.setBounds(0, 0, this.getWidth(), this.getHeight());

        desktop_menu = new JDesktopPane();
        desktop_menu.add(backgroundLabel, new Integer(Integer.MIN_VALUE)); // Agregar el JLabel detrás de los demás componentes
        desktop_menu.setBounds(0, 0, this.getWidth(), this.getHeight());
        

        this.setContentPane(desktop_menu);
        
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuVeterinario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuGestDuenios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuGestionMascotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuAggHisto = new javax.swing.JMenuItem();
        MenuVerHisto = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(270, 50));
        setSize(new java.awt.Dimension(0, 0));

        jMenu1.setBackground(new java.awt.Color(129, 148, 216));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu Veterinario.png"))); // NOI18N
        jMenu1.setText("Veterinario                                    ");
        jMenu1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(270, 50));

        MenuVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GestionVet.png"))); // NOI18N
        MenuVeterinario.setText("Gestionar Veterinario");
        MenuVeterinario.setPreferredSize(new java.awt.Dimension(270, 30));
        MenuVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVeterinarioActionPerformed(evt);
            }
        });
        jMenu1.add(MenuVeterinario);

        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(129, 148, 216));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DueñoYMacota.png"))); // NOI18N
        jMenu3.setText("Dueños");
        jMenu3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(270, 50));

        MenuGestDuenios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DueñoMasco.png"))); // NOI18N
        MenuGestDuenios.setText("Gestionar Dueños");
        MenuGestDuenios.setPreferredSize(new java.awt.Dimension(270, 30));
        MenuGestDuenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGestDueniosActionPerformed(evt);
            }
        });
        jMenu3.add(MenuGestDuenios);

        jMenuBar1.add(jMenu3);

        jMenu2.setBackground(new java.awt.Color(129, 148, 216));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mascotas.png"))); // NOI18N
        jMenu2.setText("Mascotas");
        jMenu2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(270, 50));

        MenuGestionMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informe-medico.png"))); // NOI18N
        MenuGestionMascotas.setText("Gestionar Mascotas");
        MenuGestionMascotas.setPreferredSize(new java.awt.Dimension(270, 30));
        MenuGestionMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGestionMascotasActionPerformed(evt);
            }
        });
        jMenu2.add(MenuGestionMascotas);

        jMenuBar1.add(jMenu2);

        jMenu4.setBackground(new java.awt.Color(129, 148, 216));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HistorialMedico.png"))); // NOI18N
        jMenu4.setText("Consultas");
        jMenu4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(270, 50));

        MenuAggHisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prescripcion-medica.png"))); // NOI18N
        MenuAggHisto.setText("Agregar Historial");
        MenuAggHisto.setPreferredSize(new java.awt.Dimension(270, 30));
        MenuAggHisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAggHistoActionPerformed(evt);
            }
        });
        jMenu4.add(MenuAggHisto);

        MenuVerHisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerHistorialPerro.png"))); // NOI18N
        MenuVerHisto.setText("Ver Historial");
        MenuVerHisto.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuVerHisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerHistoActionPerformed(evt);
            }
        });
        jMenu4.add(MenuVerHisto);

        jMenuBar1.add(jMenu4);

        jMenu7.setBackground(new java.awt.Color(129, 148, 216));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        jMenu7.setText("Cerrar session");
        jMenu7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jMenu7.setMinimumSize(new java.awt.Dimension(305, 50));
        jMenu7.setPreferredSize(new java.awt.Dimension(308, 50));

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jMenuItem12.setText("Cerrar");
        jMenuItem12.setPreferredSize(new java.awt.Dimension(270, 30));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem12);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVeterinarioActionPerformed
    
        InterVeterinario IV = new InterVeterinario();
        Principal.desktop_menu.add(IV);
        IV.setVisible(true);
        
    }//GEN-LAST:event_MenuVeterinarioActionPerformed

    private void MenuGestionMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestionMascotasActionPerformed
        GestionarMascotas GM = new GestionarMascotas();
        Principal.desktop_menu.add(GM);
        GM.setVisible(true);
    }//GEN-LAST:event_MenuGestionMascotasActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Login log = new Login();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void MenuGestDueniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestDueniosActionPerformed
        GestionarDuenios DM= new GestionarDuenios();
        Principal.desktop_menu.add(DM);
        DM.setVisible(true);
    }//GEN-LAST:event_MenuGestDueniosActionPerformed

    private void MenuAggHistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAggHistoActionPerformed
        HistorialMedico HM = new HistorialMedico();
        Principal.desktop_menu.add(HM);
        HM.setVisible(true);
    }//GEN-LAST:event_MenuAggHistoActionPerformed

    private void MenuVerHistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerHistoActionPerformed
       VerHistorial VH = new VerHistorial();
       Principal.desktop_menu.add(VH);
       VH.setVisible(true);
    }//GEN-LAST:event_MenuVerHistoActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAggHisto;
    private javax.swing.JMenuItem MenuGestDuenios;
    private javax.swing.JMenuItem MenuGestionMascotas;
    private javax.swing.JMenuItem MenuVerHisto;
    private javax.swing.JMenuItem MenuVeterinario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem12;
    // End of variables declaration//GEN-END:variables
}
