
package GUI;


import LOGIC.Validacion;

import SQL.Conexion;

import LOGIC.HistorialMedicos;
import java.awt.BorderLayout;


import java.util.ArrayList;

import java.util.List;
import javax.swing.JScrollPane;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;




/**
 *
 * @author dylan
 */
public class VerHistorial extends javax.swing.JInternalFrame 
{

    Validacion val = null;
    Conexion conect = null;
    private DefaultTableModel tabla;
    public VerHistorial() 
    {
        initComponents();
        val = new Validacion();
        val.centrarInternalFrame(this, Principal.desktop_menu);

        tabla = new DefaultTableModel();

        cargarTabla();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tabla);
        TablaHisto.setRowSorter(sorter);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVerReg = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHisto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDeshacer = new javax.swing.JButton();
        Busqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(1070, 580));
        setMinimumSize(new java.awt.Dimension(1070, 580));
        setPreferredSize(new java.awt.Dimension(1070, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Ver Historiales");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Busqueda:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        btnVerReg.setBackground(new java.awt.Color(255, 255, 255));
        btnVerReg.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnVerReg.setForeground(new java.awt.Color(102, 102, 102));
        btnVerReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HistorialMedico.png"))); // NOI18N
        btnVerReg.setText("Ver Historial de");
        btnVerReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnVerReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 30));

        TablaHisto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaHisto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 510, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 510, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 195, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 195, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1020, 390));

        btnDeshacer.setBackground(new java.awt.Color(4, 231, 252));
        btnDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/deshacer(1).png"))); // NOI18N
        btnDeshacer.setBorder(null);
        btnDeshacer.setBorderPainted(false);
        btnDeshacer.setFocusable(false);
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 20, 40));

        Busqueda.setBackground(new java.awt.Color(255, 255, 255));
        Busqueda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 180, -1));

        btnBuscar.setBackground(new java.awt.Color(4, 231, 252));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-de-lupa(1).png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setFocusable(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 30, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerHistorial.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tabla);
        TablaHisto.setRowSorter(sorter);
    
        List<RowFilter<Object, Object>> filters = new ArrayList<>();
        int[] columnasABuscar = {1, 4};

        for (int columna : columnasABuscar) {
            filters.add(RowFilter.regexFilter("(?i)" + Busqueda.getText(), columna));
        }

        RowFilter<Object, Object> rowFilter = RowFilter.orFilter(filters);
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerActionPerformed
         TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>) TablaHisto.getRowSorter();
         sorter.setRowFilter(null);;
    }//GEN-LAST:event_btnDeshacerActionPerformed

    private void btnVerRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRegActionPerformed
       val = new Validacion();
       
       if(TablaHisto.getRowCount()>0)
       {
           if(TablaHisto.getSelectedColumn() != -1)
           {
               int id = Integer.parseInt(String.valueOf(TablaHisto.getValueAt(TablaHisto.getSelectedRow(), 1)));
               VistaDeHistorial VDH = new VistaDeHistorial(id);
               Principal.desktop_menu.add(VDH);
               VDH.setVisible(true);
           }
           
           else
           {
               val.mostrarMensaje("No se selecciono ningun registro", "Error", "Error al seleccionar");
               return;
           }
       }
       
    }//GEN-LAST:event_btnVerRegActionPerformed

    public void cargarTabla()
    {
            tabla.setRowCount(0);
          tabla = new DefaultTableModel() 
          {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
            conect = new Conexion();
            String[] titulos = {
                "<html><b><font face='Liberation Sans' size='4'>ID</font></b></html>",
                "<html><b><font face='Liberation Sans' size='3.4'>MascotaID</font></b></html>",
                "<html><b><font face='Liberation Sans' size='3.4'>VeterinarioID</font></b></html>",
                "<html><b><font face='Liberation Sans' size='4'>Fecha Visita</font></b></html>",
                "<html><b><font face='Liberation Sans' size='4'>Motivo Visita</font></b></html>",
                "<html><b><font face='Liberation Sans' size='4'>Fecha Vacuna</font></b></html>",
                "<html><b><font face='Liberation Sans' size='4'>Nombre Vacuna</font></b></html>",
                "<html><b><font face='Liberation Sans' size='4'>Desparasitacion</font></b></html>",
                "<html><b><font face='Liberation Sans' size='4'>Descripcion</font></b></html>",
                "<html><b><font face='Liberation Sans' size='4'>Medicamentos</font></b></html>"
            };

            tabla.setColumnIdentifiers(titulos);
            List<HistorialMedicos> ListHisto = conect.traerHistorialMedico();

            if (ListHisto != null)
            {
                for (HistorialMedicos histo : ListHisto)
                {
                    Object[] objeto = {
                        histo.getId(),
                        histo.getMascotaID(),
                        histo.getVeterinarioID(),
                        histo.getFechaVisita(),
                        histo.getMotivoVisita(),
                        histo.getFechaVacuna(),
                        histo.getNombreVacuna(),
                        histo.getDesparasitacion(),
                        histo.getDescripcion(),
                        histo.getMedicamentos()
                    };
                    tabla.addRow(objeto);
                }
            }

            TablaHisto.setModel(tabla);
            TableColumnModel columnModel = TablaHisto.getColumnModel();
            int ancho = 90;
            columnModel.getColumn(0).setPreferredWidth(ancho);
            columnModel.getColumn(0).setMaxWidth(ancho);
            columnModel.getColumn(0).setMinWidth(ancho);
            columnModel.getColumn(1).setPreferredWidth(ancho);
            columnModel.getColumn(1).setMaxWidth(ancho);
            columnModel.getColumn(1).setMinWidth(ancho);
            columnModel.getColumn(2).setPreferredWidth(ancho);
            columnModel.getColumn(2).setMaxWidth(ancho);
            columnModel.getColumn(2).setMinWidth(ancho);
            columnModel.getColumn(3).setMaxWidth(150);
            columnModel.getColumn(3).setMinWidth(150);
            columnModel.getColumn(3).setPreferredWidth(150);
            columnModel.getColumn(4).setMaxWidth(150);
            columnModel.getColumn(4).setMinWidth(150);
            columnModel.getColumn(4).setPreferredWidth(150);
            columnModel.getColumn(5).setMaxWidth(150);
            columnModel.getColumn(5).setMinWidth(150);
            columnModel.getColumn(5).setPreferredWidth(150);
            columnModel.getColumn(6).setMaxWidth(150);
            columnModel.getColumn(6).setMinWidth(150);
            columnModel.getColumn(6).setPreferredWidth(150);
            columnModel.getColumn(7).setMaxWidth(150);
            columnModel.getColumn(7).setMinWidth(150);
            columnModel.getColumn(7).setPreferredWidth(150);
             columnModel.getColumn(8).setMaxWidth(100);
            columnModel.getColumn(8).setMinWidth(100);
            columnModel.getColumn(8).setPreferredWidth(100);
            columnModel.getColumn(9).setMaxWidth(100);
            columnModel.getColumn(9).setMinWidth(100);
            columnModel.getColumn(9).setPreferredWidth(100);
              
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            TablaHisto.setDefaultRenderer(Object.class, centerRenderer);
            TablaHisto.getTableHeader().setReorderingAllowed(false);

            for (int i = 0; i < columnModel.getColumnCount(); i++) 
            {
                columnModel.getColumn(i).setResizable(false);
            }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Busqueda;
    private javax.swing.JTable TablaHisto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnVerReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
